#!/bin/env bash 

set -xe

ETCD_VERSION=3.3.11
COREDNS_VERSION=1.3.1
HostIP=$(ip route get 1.1.1.1 | awk 'NR==1 { print $7 }')
ETCD_CONTAINER_NAME=coredns-etcd
COREDNS_CONTAINER_NAME=coredns

## Start the etcd backend
### NOTE: Added 0.0.0.0 to advertised client urls to allow direct container communication
podman pull quay.io/coreos/etcd:v${ETCD_VERSION}
podman stop ${ETCD_CONTAINER_NAME} && podman rm ${ETCD_CONTAINER_NAME}
podman run -d \
  -v /usr/share/ca-certificates/:/etc/ssl/certs \
  -p 4001:4001 -p 2380:2380 -p 2379:2379 \
  --name ${ETCD_CONTAINER_NAME} \
  quay.io/coreos/etcd:v${ETCD_VERSION} etcd \
    -name etcd0 \
    -advertise-client-urls http://${HostIP}:2379,http://${HostIP}:4001,http://0.0.0.0:2379,http://0.0.0.0:4001 \
    -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
    -initial-advertise-peer-urls http://${HostIP}:2380  \
    -listen-peer-urls http://0.0.0.0:2380 \
    -initial-cluster-token etcd-cluster-1 \
    -initial-cluster etcd0=http://${HostIP}:2380 \
    -initial-cluster-state new

etcd_ip=$(podman inspect ${ETCD_CONTAINER_NAME} | jq -r '.[].NetworkSettings.IPAddress')

## Start CoreDNS
### Pull and run container with above config
podman pull docker.io/coredns/coredns:${COREDNS_VERSION}
podman stop ${COREDNS_CONTAINER_NAME} && podman rm ${COREDNS_CONTAINER_NAME}
podman run -d \
  --name ${COREDNS_CONTAINER_NAME} \
  -v ${PWD}/config:/data:ro \
  --env ETCD_IP=${HostIP} \
  --network host \
  --publish 53:53/udp \
  docker.io/coredns/coredns:${COREDNS_VERSION} -conf /data/Corefile

coredns_ip=$(podman inspect coredns | jq -r '.[].NetworkSettings.IPAddress')
## Create some test data
### Add Forward entries
podman exec -ti --env=ETCDCTL_API=3 ${ETCD_CONTAINER_NAME} /usr/local/bin/etcdctl \
  put /skydns/pub/msk/bigdata "{\"host\":\"${HostIP}\",\"ttl\":60}"

### Reverse entries
podman exec -ti --env=ETCDCTL_API=3 ${ETCD_CONTAINER_NAME} /usr/local/bin/etcdctl \
  put /skydns/arpa/in-addr/$(echo $HostIP | tr '.' '/') '{"host": "bigdata.msk.pub"}'

### Check resolution
dig +short bigdata.msk.pub @${HostIP}
dig +short -x ${HostIP} @${HostIP}

### Systemd
cp -rf systemd/*.service /etc/systemd/system/
systemctl enable coredns
systemctl enable coredns-etcd
